Ais\PertemuanMahasiswaBundle\Entity\PertemuanMahasiswa:
 type: entity
 table: pertemuan_mahasiswa
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  pertemuan_id:
   type: integer
  mahasiswa_id:
   type: integer
  kehadiran:
   type: integer
   length: 2
  keterangan:
   type: text
  is_delete:
   type: boolean
   nullable: true
