<?php

namespace Ais\PertemuanMahasiswaBundle\Repository;

/**
 * PertemuanMahasiswaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PertemuanMahasiswaRepository extends \Doctrine\ORM\EntityRepository
{
}
